title: Café com Pimenta
author:
  name: AEROGAMI
metadata:
    description: 'Para você ter reuniões mais produtivas, com a garantia de alimentos frescos e energéticos, através de um serviço personalizado de coffee breaks.'
    
# Header customization
header:
  title: "uma pausa para o café."
